
simple:
  tournament: latest
  pages:
    - { tz: US/Pacific  }

navid:
  tournament: latest
  file_suffix: navid
  pages:
    - { tz: Asia/Tehran,         loc: fa_IR }
    - { tz: Europe/Amsterdam,    loc: fa_IR }
    - { tz: Europe/Amsterdam,    loc: en_GB }
    - { tz: Europe/Amsterdam,    loc: nl_NL }

hans:
  tournament: latest
  file_suffix: hans
  pages:
    - { tz: US/Pacific, format: a1, loc: en_US  }
    - { tz: US/Pacific, format: a1, loc: es_US  }
    - { tz: US/Pacific, format: a1, loc: zh_Hans_CN  }

hant:
  tournament: latest
  file_suffix: hant
  pages:
    - { tz: US/Pacific, format: a1, loc: en_US  }
    - { tz: US/Pacific, format: a1, loc: zh_Hans_CN  }

ko:
  tournament: latest
  file_suffix: ko
  pages:
    - { tz: US/Pacific, format: a1, loc: en_US  }
    - { tz: US/Pacific, format: a1, loc: ko_KR  }

tests:
  tournament: latest
  file_suffix: tests
  pages:
    - page_kind: groups_test
    - page_kind: days_test

designs:
  tournament: latest
  file_suffix: designs
  pages:
    - page_kind: cal_only
      variant: alpha
      match_numbers: true
      elimination_hints: false
      group_dots: false
    
    - variant: beta
      elimination_borders: false
      match_numbers: true
      elimination_hints: false
      group_dots: false
    
    - variant: borderless
      main_borders: false
    
    - variant: gold master

results:
  pages:
    - { tournament: 2018-mens-world-cup  }
    - { tournament: 2022-mens-world-cup  }
    - { tournament: 2023-womens-world-cup  }
    - { tournament: 2024-mens-copa-america  }
    - { tournament: 2024-mens-euro  }
    - { tournament: 2025-mens-club-world-cup  }

tourneys:
  all_tournaments: true
  pages:
    - { tz: US/Pacific  }

langs:
  default: true
  tournament: latest
  file_suffix: langs
  pages:
    - { tz: US/Pacific  }

    # see SPageArgs for loc codes
    
    # Europe
    - { tz: Europe/London,       loc: en_GB }
    - { tz: Europe/Paris,        loc: fr_FR }
    - { tz: Europe/Madrid,       loc: es_ES }
    - { tz: Europe/Lisbon,       loc: pt_PT }
    - { tz: Europe/Rome,         loc: it_IT }
    - { tz: Europe/Berlin,       loc: de_DE }
    - { tz: Europe/Amsterdam,    loc: nl_NL }
    
    # Middle East
    - { tz: Asia/Tehran,         loc: fa_IR }
    
    # Asia
    - { tz: Asia/Tokyo,          loc: ja_JP }
    - { tz: Asia/Seoul,          loc: ko_KR }
    - { tz: Asia/Shanghai,       loc: zh_Hans_CN }
    - { tz: Asia/Taipei,         loc: zh_Hant_TW }

    # Oceania
    - { tz: Australia/Sydney,    loc: en_AU }
    - { tz: Pacific/Auckland,    loc: en_NZ }

published:
  tournament: latest
  output_dir: published
  file_suffix: all
  unwind_pages: true
  pages:
    # US Timezones
    - { tz: US/Pacific  }
    - { tz: US/Mountain }
    - { tz: US/Central  }
    - { tz: US/Eastern  }

    # European languages
    - { tz: Europe/London,       loc: en_GB }
    - { tz: Europe/Paris,        loc: fr_FR }
    - { tz: Europe/Madrid,       loc: es_ES }
    - { tz: Europe/Lisbon,       loc: pt_PT }
    - { tz: Europe/Rome,         loc: it_IT }
    - { tz: Europe/Berlin,       loc: de_DE }
    - { tz: Europe/Amsterdam,    loc: nl_NL }
    
    # Persian variants
    - { tz: Europe/Amsterdam,    loc: fa_IR }
    - { tz: Asia/Tehran,         loc: fa_IR }
    
    # Asian/Pacific
    - { tz: Asia/Tokyo,          loc: ja_JP }
    - { tz: Asia/Seoul,          loc: ko_KR }
    - { tz: Asia/Shanghai,       loc: zh_Hans_CN }
    - { tz: Asia/Taipei,         loc: zh_Hant_TW }

    # Oceania
    - { tz: Australia/Sydney,    loc: en_AU }
    - { tz: Pacific/Auckland,    loc: en_NZ }