# timezones: https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
# languages: https://en.wikipedia.org/wiki/List_of_ISO_639_language_codes
# countries: https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2

simple:
  tournament: latest
  pages:
    - { tz: US/Pacific  }

navid:
  tournament: latest
  file_suffix: navid
  pages:
    - { tz: Asia/Tehran,         loc: fa_IR }
    - { tz: Europe/Amsterdam,    loc: fa_IR }
    - { tz: Europe/Amsterdam,    loc: en_GB }
    - { tz: Europe/Amsterdam,    loc: nl_NL }

hans:
  tournament: latest
  file_suffix: hans
  pages:
    - { tz: US/Pacific, format: a1, loc: en_US  }
    - { tz: US/Pacific, format: a1, loc: es_US  }
    - { tz: US/Pacific, format: a1, loc: zh_CN  }

hant:
  tournament: latest
  file_suffix: hant
  pages:
    - { tz: US/Pacific, format: a1, loc: en_US  }
    - { tz: US/Pacific, format: a1, loc: zh_TW  }

ko:
  tournament: latest
  file_suffix: ko
  pages:
    - { tz: US/Pacific, format: a1, loc: en_US  }
    - { tz: US/Pacific, format: a1, loc: ko_KR  }

tests:
  tournament: latest
  file_suffix: tests
  pages:
    - page_kind: groups_test
    - page_kind: days_test

designs:
  tournament: latest
  file_suffix: designs
  pages:
    - page_kind: cal_only
      variant: alpha
      match_numbers: true
      elimination_hints: false
      group_dots: false
    
    - variant: beta
      elimination_borders: false
      match_numbers: true
      elimination_hints: false
      group_dots: false
    
    - variant: borderless
      main_borders: false
    
    - variant: gold master

results:
  pages:
    - { tournament: 2018-mens-world-cup  }
    - { tournament: 2022-mens-world-cup  }
    - { tournament: 2023-womens-world-cup  }
    - { tournament: 2024-mens-copa-america  }
    - { tournament: 2024-mens-euro  }
    - { tournament: 2025-mens-club-world-cup  }

tourneys:
  all_tournaments: true
  pages:
    - { tz: US/Pacific  }

langs:
  default: true
  tournament: latest
  file_suffix: langs
  pages:
    - { tz: US/Pacific  }

    # see SPageArgs for loc codes
    
    # Europe
    - { tz: Europe/London,       loc: en_GB }
    - { tz: Europe/Paris,        loc: fr_FR }
    - { tz: Europe/Madrid,       loc: es_ES }
    - { tz: Europe/Lisbon,       loc: pt_PT }
    - { tz: Europe/Rome,         loc: it_IT }
    - { tz: Europe/Berlin,       loc: de_DE }
    - { tz: Europe/Amsterdam,    loc: nl_NL }

    - { tz: Europe/Istanbul,     loc: tr_TR }
    - { tz: Europe/Moscow,       loc: ru_RU }

    # Africa

    - { tz: Africa/Abidjan,      loc: fr_CI }
    - { tz: Africa/Casablanca,   loc: ar_MA }
    - { tz: Africa/Johannesburg, loc: en_ZA }
    - { tz: Africa/Cairo,        loc: ar_EG }
    
    # Middle East

    - { tz: Asia/Tehran,         loc: fa_IR }
    - { tz: Asia/Riyadh,         loc: ar_SA }
    
    # Asia
    - { tz: Asia/Tokyo,          loc: ja_JP }
    - { tz: Asia/Seoul,          loc: ko_KR }
    - { tz: Asia/Shanghai,       loc: zh_CN }
    - { tz: Asia/Taipei,         loc: zh_TW }
    - { tz: Asia/Kolkata,        loc: en_IN }

    # Oceania
    - { tz: Australia/Sydney,    loc: en_AU }
    - { tz: Pacific/Auckland,    loc: en_NZ }

published:
  tournament: latest
  output_dir: playground/published
  file_suffix: all
  unwind_pages: true
  pages:

    # US

    - { tz: America/Los_Angeles,  loc: en_US }
    - { tz: America/Denver,       loc: en_US }
    - { tz: America/Chicago,      loc: en_US }
    - { tz: America/New_York,     loc: en_US }
    - { tz: America/Anchorage,    loc: en_US }
    - { tz: Pacific/Honolulu,     loc: en_US }

    # Canada

    - { tz: America/Vancouver,    loc: en_CA }
    - { tz: America/Edmonton,     loc: en_CA }
    - { tz: America/Winnipeg,     loc: en_CA }
    - { tz: America/Regina,       loc: en_CA }
    - { tz: America/Toronto,      loc: en_CA }

    # Latin America

    - { tz: America/Tijuana,      loc: es_MX }
    - { tz: America/Mexico_City,  loc: es_MX }

    - { tz: America/Panama,       loc: es_PA }
    - { tz: America/Port-au-Prince, loc: fr_HT }
    - { tz: America/Curacao,      loc: nl_CW }
 
    - { tz: America/Bogota,       loc: es_CO }
    - { tz: America/Guayaquil,    loc: es_EC }
    - { tz: America/Buenos_Aires, loc: es_AR }
    - { tz: America/Montevideo,   loc: es_UY }
    - { tz: America/Asuncion,     loc: es_PA }
    - { tz: America/Sao_Paulo,    loc: pt_BR }

    # Europe

    - { tz: Europe/London,       loc: en_GB }
    - { tz: Europe/Paris,        loc: fr_FR }
    - { tz: Europe/Madrid,       loc: es_ES }
    - { tz: Europe/Lisbon,       loc: pt_PT }
    - { tz: Europe/Rome,         loc: it_IT }
    - { tz: Europe/Berlin,       loc: de_DE }
    - { tz: Europe/Amsterdam,    loc: nl_NL }

    - { tz: Europe/Oslo,         loc: nb_NO }
    - { tz: Europe/Stockholm,    loc: sv_SE }
    - { tz: Europe/Brussels,     loc: nl_BE }
    - { tz: Europe/Zurich,       loc: de_CH }
    - { tz: Europe/Vienna,       loc: de_AT }
    - { tz: Europe/Prague,       loc: cs_CZ }
    - { tz: Europe/Sarajevo,     loc: hr_BA }
    - { tz: Europe/Zagreb,       loc: hr_HR }
    - { tz: Europe/Istanbul,     loc: tr_TR }
    - { tz: Europe/Moscow,       loc: ru_RU }
    
    # Africa

    - { tz: Atlantic/Cape_Verde, loc: pt_CV }
    - { tz: Africa/Abidjan,      loc: fr_CI }
    - { tz: Africa/Casablanca,   loc: ar_MA }
    - { tz: Africa/Johannesburg, loc: en_ZA }
    - { tz: Africa/Cairo,        loc: ar_EG }
    
    # Middle East

    - { tz: Asia/Tehran,         loc: fa_IR }
    - { tz: Asia/Riyadh,         loc: ar_SA }
    - { tz: Asia/Tashkent,       loc: uz_UZ }
    
    # Asian/Pacific

    - { tz: Asia/Kolkata,        loc: en_IN }
    - { tz: Asia/Tokyo,          loc: ja_JP }
    - { tz: Asia/Seoul,          loc: ko_KR }
    - { tz: Asia/Shanghai,       loc: zh_CN }
    - { tz: Asia/Taipei,         loc: zh_TW }

    # Oceania

    - { tz: Australia/Perth,     loc: en_AU }
    - { tz: Australia/Adelaide,  loc: en_AU }
# same as sydney during their winter.
#    - { tz: Australia/Brisbane,  loc: en_AU }
    - { tz: Australia/Sydney,    loc: en_AU }
    - { tz: Pacific/Auckland,    loc: en_NZ }